@startuml
class object.Joueur {
~ Keyinput entrerClavier
+ int screenX
+ int screenY
- int invincibletimer
+ int countHasEclair
+ int countHasStar
+ int frameMaxHasObject
+ boolean hasEclair
+ boolean hasStar
~ int ashEclair
+ void positionetvitessededepart()
+ void imageUpload()
+ int update()
+ int TakeObject(int)
+ void interactMonstre(int)
+ void draw(Graphics2D)
}

class game.Jeu {
~ int tailleDeBase
~ int echelle
+ int tailleCarreaux
+ int colonneEcran
+ int ligneEcran
+ int largeurEcran
+ int hauteurEcran
+ Boolean gameover
+ int maxWorldColonne
+ int maxWorldLigne
+ int hauteurWorld
+ int largeurWorld
~ int FPS
~ Random random
+ int valeatoire
~ GestionDecor gestionD
+ Keyinput entrerClavier
~ Sound sound
+ Gestionnaire gestion
~ Thread gameThread
+ VerifierCollision Verifier
+ Setter set
+ Boolean gamestart
+ Boolean endgame
+ Boolean destroy
+ Boolean victoire
+ Joueur joueur
+ SuperBonus[] obj
+ Parentsobject[] monstre
+ Parentsobject[] Fmonstre
+ void setUpGame()
+ void startGameThread()
+ void run()
+ void preupdate()
+ void update()
+ int getBonhommevie(int)
+ void paintComponent(Graphics)
+ void playMusic(int)
+ void stopMusic()
+ void playSE(int)
}
class bonus.SuperBonus {
+ BufferedImage image
+ String name
+ boolean collision
+ int worldX
+ Rectangle solidArea
+ int solidAreaDefaultX
+ int solidAreaDefaultY
+ String direction
+ int speed
+ void draw(Graphics2D,Jeu)
}

class game.Keyinput {
+ boolean toucheZ
+ void keyTyped(KeyEvent)
+ void keyPressed(KeyEvent)
+ void keyReleased(KeyEvent)
}
class game.VerifierCollision {
~ Jeu nouveaujeu
+ void VerifierDecor(Parentsobject)
+ int VerifierBonus(Parentsobject,boolean)
+ int VerifierBonus2(Joueur)
+ int VerifierParentsObject(Parentsobject,Parentsobject[])
+ void checkPlayer(Parentsobject)
}
class monstre.Fantome {
+ void getImage()
+ void setAction()
}

class bonus.ObjFlower {
}
class bonus.ObjStar {
}
class game.Sound {
~ Clip clip
~ URL[] soundURL
+ void setFile(int)
+ void play()
+ void loop()
+ void stop()
}
class object.Parentsobject {
~ Jeu nouveaujeu
+ int worldX
+ int speed
+ int vie
+ BufferedImage up1
+ String direction
+ int spriteCounter
+ int spriteNum
+ Rectangle solidArea
+ int solidAreaDefaultX
+ boolean CollisionOn
+ int actionLockCounter
+ void setAction()
+ void updateSansCollision()
+ void updateAvecCollision()
+ void draw(Graphics2D)
+ BufferedImage setup(String)
+ int getVie()
+ void setVie(int)
}
class game.Gestionnaire {
~ Jeu nouveaujeu
~ Font arial_40
~ Font book_antique
~ Font header
~ BufferedImage gameover
+ void draw(Graphics2D)
+ void drawstart(Graphics2D)
+ void drawend(Graphics2D)
+ void drawvictoire(Graphics2D)
}
class bonus.ObjDrapeau {
}
class game.Main {
+ {static} void main(String[])
}
class bonus.ObjEclair {
}
class game.Window {
~ {static} JFrame window2
+ {static} void init()
+ {static} void start(Jeu)
+ {static} void destroy()
}
class monstre.Bonhomme {
+ void getImage()
+ void setAction()
+ int getBonhommmevie()
}
class bonus.ObjDrapeau {
}

class game.Setter {
~ Jeu nouveaujeu
+ Jeu getNouveaujeu()
+ void setObjects()
+ void setMonstre()
+ int getObjectX(int)
- int getObjectY(int)
}


object.Parentsobject <|-- object.Joueur
game.Runnable <|.. game.Jeu
javax.swing.JPanel <|-- game.Jeu
java.awt.event.KeyListener <|.. game.Keyinput
object.Parentsobject <|-- monstre.Fantome
bonus.SuperBonus <|-- bonus.ObjFlower
bonus.SuperBonus <|-- bonus.ObjStar
bonus.SuperBonus <|-- bonus.ObjDrapeau
bonus.SuperBonus <|-- bonus.ObjEclair
object.Parentsobject <|-- monstre.Bonhomme
bonus.SuperBonus <|-- bonus.ObjDrapeau
game.Gestionnaire -- game.Jeu
game.VerifierCollision .. object.Parentsobject
game.Window -- game.Jeu
game.Main <-- game.Window
game.Setter <-- bonus.SuperBonus
game.Setter -- game.Jeu
game.Sound -- game.Jeu
game.VerifierCollision -- game.Jeu
@enduml